# Generated by Django 4.1 on 2024-06-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('identification', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('identification', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('score1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extension', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observation', models.CharField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradedetails', to='core.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.period'),
        ),
        migrations.AddField(
            model_name='grade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.professor'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.subject'),
        ),
    ]
