# Generated by Django 4.1 on 2024-06-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grade_updated_gradedetail_updated_period_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='identification',
            new_name='idcard',
        ),
    ]
