# Generated by Django 4.1 on 2024-06-11 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_identification_professor_idcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='name',
        ),
        migrations.AddField(
            model_name='period',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='period',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='period',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
