# Generated by Django 4.1 on 2024-06-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_identification_student_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedetail',
            name='observation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
